<?php

namespace App\Http\Controllers\Doctor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Appointment;
use App\Models\Diagnosis;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Http;

class AIScribeController extends Controller
{
    public function process(Request $request)
    {
        $request->validate([
            'audio' => 'required|file|mimes:wav,mp3,m4a,webm',
            'appointment_id' => 'required|exists:appointments,id'
        ]);

        $file = $request->file('audio');
        $appointmentId = $request->appointment_id;
        
        // 1. Store File Temporarily
        $path = $file->storeAs('temp_audio', "scribe_{$appointmentId}.wav");
        $fullPath = storage_path('app/' . $path);

        // 2. Call OpenAI Whisper API (Stubbed)
        // In production, you would retrieve the API Key from config('services.openai.key')
        // $text = $this->transcribeAudio($fullPath);
        
        // MOCK RESPONSE for Demo
        // Simulating that the doctor said: "Patient complains of headache and fever..."
        $simulatedText = "Patient presents with severe migraine and sensitivity to light. Has been recurring for 3 days. BP is 120/80. Prescribed Paracetamol 500mg twice daily.";

        // 3. Process Text to Extract Structural Data (Stubbed LLM Call)
        // $structuredData = $this->extractMedicalData($simulatedText);
        
        // MOCK Extraction
        $notes = $simulatedText;
        $diagnosisName = "Migraine"; 
        $symptoms = "Headache, Photophobia";

        // 4. Save to Database
        // Check if diagnosis exists, else create
        $diagnosis = Diagnosis::updateOrCreate(
            ['appointment_id' => $appointmentId],
            [
                'diagnosis' => $diagnosisName,
                'symptoms' => $symptoms,
                'notes' => $notes . "\n\n(Generated by AI Scribe)"
            ]
        );

        // Cleanup
        Storage::delete($path);

        return response()->json([
            'success' => true, 
            'message' => 'Processed',
            'text' => $simulatedText
        ]);
    }
}
